import type { CardDefinition } from "@towerlab/core";

type CardRarity = "common" | "rare" | "epic";

type CardTemplate = {
  id: string;
  name: string;
  cost: number;
  description: string;
  keywords?: Array<"exhaust" | "retain" | "ethereal">;
  damage?: number;
  block?: number;
  draw?: number;
  energy?: number;
  heal?: number;
  weak?: number;
  vulnerable?: number;
  poison?: number;
  poisonMultiplier?: number;
  exhaust?: boolean;
  retain?: boolean;
};

const CARD_RARITY_BY_ID: Record<string, CardRarity> = {
  uppercut: "rare",
  carnage: "rare",
  battleTrance: "rare",
  bloodletting: "rare",
  secondWind: "rare",
  shockwave: "rare",
  heavyBlow: "rare",
  warpath: "rare",
  overrun: "rare",
  clothesline: "rare",
  dropkick: "rare",
  ghostlyArmor: "rare",
  seeingRed: "rare",
  offering: "rare",
  outmaneuver: "rare",
  legSweep: "rare",
  dash: "rare",
  predator: "rare",
  cripplingCloud: "rare",
  catalyst: "rare",
  piercingWail: "rare",
  bouncingFlask: "rare",
  heelHook: "rare",
  deadlyTactics: "rare",
  impervious: "epic",
  bludgeon: "epic",
  executioner: "epic",
  finalCharge: "epic",
  burningBanner: "epic",
  warSpoils: "epic",
  reaper: "epic",
  glassKnife: "epic",
  adrenaline: "epic",
  finisher: "epic",
};

const baseCards: Record<string, CardTemplate> = {
  battleJab: {
    id: "battleJab",
    name: "Battle Jab",
    cost: 0,
    description: "Deal 4 damage.",
    damage: 4,
  },
  strike: {
    id: "strike",
    name: "Strike",
    cost: 1,
    description: "Deal 6 damage.",
    damage: 6,
  },
  defend: {
    id: "defend",
    name: "Defend",
    cost: 1,
    description: "Gain 5 block.",
    block: 5,
  },
  surge: {
    id: "surge",
    name: "Surge",
    cost: 1,
    description: "Deal 4 damage. Gain 4 block.",
    damage: 4,
    block: 4,
  },
  frontlineGuard: {
    id: "frontlineGuard",
    name: "Frontline Guard",
    cost: 1,
    description: "Gain 8 block.",
    block: 8,
  },
  advanceStep: {
    id: "advanceStep",
    name: "Advance Step",
    cost: 1,
    description: "Deal 5 damage. Gain 2 block.",
    damage: 5,
    block: 2,
  },
  quickGuard: {
    id: "quickGuard",
    name: "Quick Guard",
    cost: 1,
    description: "Gain 7 block.",
    block: 7,
  },
  sunderStrike: {
    id: "sunderStrike",
    name: "Sunder Strike",
    cost: 2,
    description: "Deal 12 damage.",
    damage: 12,
  },
  punishingHit: {
    id: "punishingHit",
    name: "Punishing Hit",
    cost: 2,
    description: "Deal 9 damage.",
    damage: 9,
  },
  heavyBlow: {
    id: "heavyBlow",
    name: "Heavy Blow",
    cost: 2,
    description: "Deal 11 damage.",
    damage: 11,
  },
  precision: {
    id: "precision",
    name: "Precision",
    cost: 2,
    description: "Deal 6 damage. Gain 2 block.",
    damage: 6,
    block: 2,
  },
  recklessLunge: {
    id: "recklessLunge",
    name: "Reckless Lunge",
    cost: 1,
    description: "Deal 8 damage.",
    damage: 8,
  },
  warCry: {
    id: "warCry",
    name: "War Cry",
    cost: 0,
    description: "Draw 1 card. Gain 1 energy.",
    keywords: ["exhaust"],
    draw: 1,
    energy: 1,
    exhaust: true,
  },
  tempoDrill: {
    id: "tempoDrill",
    name: "Tempo Drill",
    cost: 1,
    description: "Gain 1 energy. Draw 1 card.",
    energy: 1,
    draw: 1,
  },
  vanguardRecovery: {
    id: "vanguardRecovery",
    name: "Vanguard Recovery",
    cost: 1,
    description: "Recover 5 HP. Draw 1 card.",
    keywords: ["exhaust"],
    heal: 5,
    draw: 1,
    exhaust: true,
  },
  advanceSignal: {
    id: "advanceSignal",
    name: "Advance Signal",
    cost: 0,
    description: "Draw 2 cards. Gain 2 energy.",
    keywords: ["exhaust"],
    draw: 2,
    energy: 2,
    exhaust: true,
  },
  assaultSignal: {
    id: "assaultSignal",
    name: "Assault Signal",
    cost: 0,
    description: "Draw 1 card. Gain 1 energy.",
    keywords: ["exhaust"],
    draw: 1,
    energy: 1,
    exhaust: true,
  },
  vanguardVolley: {
    id: "vanguardVolley",
    name: "Vanguard Volley",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  momentum: {
    id: "momentum",
    name: "Momentum",
    cost: 1,
    description: "Deal 5 damage. Draw 1 card.",
    damage: 5,
    draw: 1,
  },
  bloodPact: {
    id: "bloodPact",
    name: "Blood Pact",
    cost: 1,
    description: "Deal 7 damage. Recover 2 HP.",
    damage: 7,
    heal: 2,
  },
  rallyLine: {
    id: "rallyLine",
    name: "Rally Line",
    cost: 1,
    description: "Gain 6 block. Draw 1 card.",
    block: 6,
    draw: 1,
  },
  forgedAdvance: {
    id: "forgedAdvance",
    name: "Forged Advance",
    cost: 1,
    description: "Gain 6 block. Draw 1 card.",
    block: 6,
    draw: 1,
  },
  rallySprint: {
    id: "rallySprint",
    name: "Rally Sprint",
    cost: 1,
    description: "Recover 4 HP. Gain 1 energy.",
    heal: 4,
    energy: 1,
  },
  stormAssault: {
    id: "stormAssault",
    name: "Storm Assault",
    cost: 2,
    description: "Deal 9 damage. Gain 1 energy.",
    damage: 9,
    energy: 1,
  },
  ironTempo: {
    id: "ironTempo",
    name: "Iron Tempo",
    cost: 2,
    description: "Deal 8 damage. Gain 6 block.",
    damage: 8,
    block: 6,
  },
  warpath: {
    id: "warpath",
    name: "Warpath",
    cost: 2,
    description: "Deal 10 damage. Gain 5 block.",
    damage: 10,
    block: 5,
  },
  crushingTempo: {
    id: "crushingTempo",
    name: "Crushing Tempo",
    cost: 2,
    description: "Deal 8 damage. Gain 8 block.",
    damage: 8,
    block: 8,
  },
  frenziedCharge: {
    id: "frenziedCharge",
    name: "Frenzied Charge",
    cost: 2,
    description: "Deal 10 damage. Gain 1 energy.",
    damage: 10,
    energy: 1,
  },
  secondWind: {
    id: "secondWind",
    name: "Second Wind",
    cost: 2,
    description: "Gain 7 block. Recover 4 HP.",
    keywords: ["exhaust"],
    block: 7,
    heal: 4,
    exhaust: true,
  },
  burningBanner: {
    id: "burningBanner",
    name: "Burning Banner",
    cost: 2,
    description: "Deal 8 damage. Draw 2 cards.",
    damage: 8,
    draw: 2,
  },
  battleTrance: {
    id: "battleTrance",
    name: "Battle Trance",
    cost: 0,
    description: "Draw 2 cards.",
    keywords: ["exhaust"],
    draw: 2,
    exhaust: true,
  },
  bloodRush: {
    id: "bloodRush",
    name: "Blood Rush",
    cost: 1,
    description: "Deal 6 damage. Gain 1 energy.",
    damage: 6,
    energy: 1,
  },
  skirmishPlan: {
    id: "skirmishPlan",
    name: "Skirmish Plan",
    cost: 1,
    description: "Draw 1 card. Gain 5 block.",
    keywords: ["retain"],
    draw: 1,
    block: 5,
    retain: true,
  },
  heldBlade: {
    id: "heldBlade",
    name: "Held Blade",
    cost: 2,
    description: "Deal 15 damage.",
    keywords: ["retain"],
    damage: 15,
    retain: true,
  },
  bash: {
    id: "bash",
    name: "Bash",
    cost: 2,
    description: "Deal 8 damage. Apply 2 Vulnerable.",
    damage: 8,
    vulnerable: 2,
  },
  pommelStrike: {
    id: "pommelStrike",
    name: "Pommel Strike",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  shrugItOff: {
    id: "shrugItOff",
    name: "Shrug It Off",
    cost: 1,
    description: "Gain 8 block. Draw 1 card.",
    block: 8,
    draw: 1,
  },
  anger: {
    id: "anger",
    name: "Anger",
    cost: 0,
    description: "Deal 4 damage.",
    damage: 4,
  },
  trueGrit: {
    id: "trueGrit",
    name: "True Grit",
    cost: 1,
    description: "Gain 7 block.",
    block: 7,
  },
  twinStrike: {
    id: "twinStrike",
    name: "Twin Strike",
    cost: 1,
    description: "Deal 8 damage.",
    damage: 8,
  },
  ironWave: {
    id: "ironWave",
    name: "Iron Wave",
    cost: 1,
    description: "Deal 5 damage. Gain 5 block.",
    damage: 5,
    block: 5,
  },
  thunderclap: {
    id: "thunderclap",
    name: "Thunderclap",
    cost: 1,
    description: "Deal 4 damage. Apply 1 Vulnerable.",
    damage: 4,
    vulnerable: 1,
  },
  disarm: {
    id: "disarm",
    name: "Disarm",
    cost: 1,
    description: "Apply 2 Weak.",
    weak: 2,
  },
  bloodletting: {
    id: "bloodletting",
    name: "Bloodletting",
    cost: 0,
    description: "Gain 2 energy.",
    keywords: ["exhaust"],
    energy: 2,
    exhaust: true,
  },
  carnage: {
    id: "carnage",
    name: "Carnage",
    cost: 2,
    description: "Deal 18 damage.",
    keywords: ["retain"],
    damage: 18,
    retain: true,
  },
  uppercut: {
    id: "uppercut",
    name: "Uppercut",
    cost: 2,
    description: "Deal 11 damage. Apply 1 Weak. Apply 1 Vulnerable.",
    damage: 11,
    weak: 1,
    vulnerable: 1,
  },
  shockwave: {
    id: "shockwave",
    name: "Shockwave",
    cost: 2,
    description: "Apply 2 Weak. Apply 2 Vulnerable.",
    keywords: ["exhaust"],
    weak: 2,
    vulnerable: 2,
    exhaust: true,
  },
  impervious: {
    id: "impervious",
    name: "Impervious",
    cost: 2,
    description: "Gain 20 block.",
    keywords: ["exhaust"],
    block: 20,
    exhaust: true,
  },
  bludgeon: {
    id: "bludgeon",
    name: "Bludgeon",
    cost: 3,
    description: "Deal 24 damage.",
    damage: 24,
  },
  clothesline: {
    id: "clothesline",
    name: "Clothesline",
    cost: 2,
    description: "Deal 12 damage. Apply 2 Weak.",
    damage: 12,
    weak: 2,
  },
  dropkick: {
    id: "dropkick",
    name: "Dropkick",
    cost: 1,
    description: "Deal 8 damage. Draw 1 card.",
    damage: 8,
    draw: 1,
  },
  ghostlyArmor: {
    id: "ghostlyArmor",
    name: "Ghostly Armor",
    cost: 1,
    description: "Gain 10 block.",
    keywords: ["ethereal"],
    block: 10,
  },
  seeingRed: {
    id: "seeingRed",
    name: "Seeing Red",
    cost: 0,
    description: "Gain 2 energy.",
    keywords: ["exhaust"],
    energy: 2,
    exhaust: true,
  },
  offering: {
    id: "offering",
    name: "Offering",
    cost: 0,
    description: "Draw 3 cards. Gain 2 energy.",
    keywords: ["exhaust"],
    draw: 3,
    energy: 2,
    exhaust: true,
  },
  overrun: {
    id: "overrun",
    name: "Overrun",
    cost: 2,
    description: "Deal 13 damage. Recover 3 HP.",
    damage: 13,
    heal: 3,
  },
  warSpoils: {
    id: "warSpoils",
    name: "War Spoils",
    cost: 2,
    description: "Deal 11 damage. Draw 2 cards.",
    damage: 11,
    draw: 2,
  },
  executioner: {
    id: "executioner",
    name: "Executioner",
    cost: 2,
    description: "Deal 14 damage.",
    damage: 14,
  },
  finalCharge: {
    id: "finalCharge",
    name: "Final Charge",
    cost: 3,
    description: "Deal 17 damage.",
    damage: 17,
  },
  reaper: {
    id: "reaper",
    name: "Reaper",
    cost: 3,
    description: "Deal 10 damage. Recover 6 HP.",
    damage: 10,
    heal: 6,
  },
  guardStep: {
    id: "guardStep",
    name: "Guard Step",
    cost: 0,
    description: "Gain 4 block.",
    block: 4,
  },
  brace: {
    id: "brace",
    name: "Brace",
    cost: 1,
    description: "Gain 7 block.",
    block: 7,
  },
  shieldJab: {
    id: "shieldJab",
    name: "Shield Jab",
    cost: 1,
    description: "Deal 6 damage. Gain 2 block.",
    damage: 6,
    block: 2,
  },
  shieldRush: {
    id: "shieldRush",
    name: "Shield Rush",
    cost: 1,
    description: "Deal 5 damage. Gain 3 block.",
    damage: 5,
    block: 3,
  },
  survey: {
    id: "survey",
    name: "Survey",
    cost: 0,
    description: "Gain 3 block. Draw 1 card.",
    block: 3,
    draw: 1,
  },
  anchorThrow: {
    id: "anchorThrow",
    name: "Anchor Throw",
    cost: 1,
    description: "Deal 5 damage. Draw 1 card.",
    damage: 5,
    draw: 1,
  },
  reserveDrill: {
    id: "reserveDrill",
    name: "Reserve Drill",
    cost: 1,
    description: "Gain 4 block. Gain 1 energy.",
    block: 4,
    energy: 1,
  },
  wardensSignal: {
    id: "wardensSignal",
    name: "Warden's Signal",
    cost: 0,
    description: "Gain 1 energy. Draw 1 card.",
    keywords: ["exhaust"],
    energy: 1,
    draw: 1,
    exhaust: true,
  },
  fortifySignal: {
    id: "fortifySignal",
    name: "Fortify Signal",
    cost: 0,
    description: "Gain 1 energy. Draw 2 cards.",
    keywords: ["exhaust"],
    energy: 1,
    draw: 2,
    exhaust: true,
  },
  fortifyDrill: {
    id: "fortifyDrill",
    name: "Fortify Drill",
    cost: 1,
    description: "Gain 7 block. Draw 1 card.",
    block: 7,
    draw: 1,
  },
  lineWard: {
    id: "lineWard",
    name: "Line Ward",
    cost: 1,
    description: "Gain 7 block. Draw 1 card.",
    block: 7,
    draw: 1,
  },
  rearGuard: {
    id: "rearGuard",
    name: "Rear Guard",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  ironAnchor: {
    id: "ironAnchor",
    name: "Iron Anchor",
    cost: 1,
    description: "Gain 4 block. Recover 3 HP.",
    block: 4,
    heal: 3,
  },
  rampartBuildup: {
    id: "rampartBuildup",
    name: "Rampart Buildup",
    cost: 2,
    description: "Gain 10 block. Recover 3 HP.",
    block: 10,
    heal: 3,
  },
  braceLine: {
    id: "braceLine",
    name: "Brace Line",
    cost: 0,
    description: "Gain 5 block.",
    block: 5,
  },
  shieldRelay: {
    id: "shieldRelay",
    name: "Shield Relay",
    cost: 1,
    description: "Gain 5 block. Draw 2 cards.",
    block: 5,
    draw: 2,
  },
  quarterWatch: {
    id: "quarterWatch",
    name: "Quarter Watch",
    cost: 1,
    description: "Gain 6 block. Gain 1 energy.",
    keywords: ["retain"],
    block: 6,
    energy: 1,
    retain: true,
  },
  watchtower: {
    id: "watchtower",
    name: "Watchtower",
    cost: 2,
    description: "Gain 11 block. Draw 1 card.",
    keywords: ["retain"],
    block: 11,
    draw: 1,
    retain: true,
  },
  siegeRam: {
    id: "siegeRam",
    name: "Siege Ram",
    cost: 2,
    description: "Deal 12 damage. Gain 7 block.",
    damage: 12,
    block: 7,
  },
  bastionCall: {
    id: "bastionCall",
    name: "Bastion Call",
    cost: 2,
    description: "Gain 11 block. Draw 2 cards.",
    block: 11,
    draw: 2,
  },
  bulwarkRecovery: {
    id: "bulwarkRecovery",
    name: "Bulwark Recovery",
    cost: 1,
    description: "Recover 4 HP. Gain 6 block.",
    keywords: ["exhaust"],
    heal: 4,
    block: 6,
    exhaust: true,
  },
  lockstep: {
    id: "lockstep",
    name: "Lockstep",
    cost: 1,
    description: "Gain 6 block. Draw 1 card.",
    block: 6,
    draw: 1,
  },
  refit: {
    id: "refit",
    name: "Refit",
    cost: 1,
    description: "Gain 5 block. Recover 3 HP.",
    keywords: ["exhaust"],
    block: 5,
    heal: 3,
    exhaust: true,
  },
  safeguard: {
    id: "safeguard",
    name: "Safeguard",
    cost: 1,
    description: "Gain 9 block.",
    block: 9,
  },
  wallStance: {
    id: "wallStance",
    name: "Wall Stance",
    cost: 1,
    description: "Gain 10 block.",
    block: 10,
  },
  gatebreaker: {
    id: "gatebreaker",
    name: "Gatebreaker",
    cost: 2,
    description: "Deal 12 damage.",
    damage: 12,
  },
  towerSlam: {
    id: "towerSlam",
    name: "Tower Slam",
    cost: 2,
    description: "Deal 11 damage. Gain 5 block.",
    damage: 11,
    block: 5,
  },
  holdFast: {
    id: "holdFast",
    name: "Hold Fast",
    cost: 1,
    description: "Gain 9 block.",
    block: 9,
  },
  riposte: {
    id: "riposte",
    name: "Riposte",
    cost: 1,
    description: "Deal 8 damage. Gain 2 block.",
    damage: 8,
    block: 2,
  },
  citadel: {
    id: "citadel",
    name: "Citadel",
    cost: 2,
    description: "Gain 9 block. Deal 7 damage.",
    damage: 7,
    block: 9,
  },
  lastStand: {
    id: "lastStand",
    name: "Last Stand",
    cost: 2,
    description: "Deal 9 damage. Gain 9 block.",
    damage: 9,
    block: 9,
  },
  aegisDrive: {
    id: "aegisDrive",
    name: "Aegis Drive",
    cost: 2,
    description: "Deal 10 damage. Gain 6 block.",
    damage: 10,
    block: 6,
  },
  aegisPulse: {
    id: "aegisPulse",
    name: "Aegis Pulse",
    cost: 2,
    description: "Gain 10 block. Draw 2 cards.",
    block: 10,
    draw: 2,
  },
  keepersOath: {
    id: "keepersOath",
    name: "Keeper's Oath",
    cost: 2,
    description: "Deal 8 damage. Recover 4 HP.",
    damage: 8,
    heal: 4,
  },
  breakFormation: {
    id: "breakFormation",
    name: "Break Formation",
    cost: 2,
    description: "Deal 11 damage. Gain 1 energy.",
    damage: 11,
    energy: 1,
  },
  bastion: {
    id: "bastion",
    name: "Bastion",
    cost: 2,
    description: "Gain 12 block.",
    block: 12,
  },
  stronghold: {
    id: "stronghold",
    name: "Stronghold",
    cost: 2,
    description: "Gain 14 block.",
    block: 14,
  },
  citadelBreaker: {
    id: "citadelBreaker",
    name: "Citadel Breaker",
    cost: 3,
    description: "Deal 14 damage. Gain 10 block.",
    damage: 14,
    block: 10,
  },
  slice: {
    id: "slice",
    name: "Slice",
    cost: 1,
    description: "Deal 5 damage.",
    damage: 5,
  },
  dodge: {
    id: "dodge",
    name: "Dodge",
    cost: 1,
    description: "Gain 5 block.",
    block: 5,
  },
  neutralize: {
    id: "neutralize",
    name: "Neutralize",
    cost: 0,
    description: "Deal 3 damage. Apply 1 Weak.",
    damage: 3,
    weak: 1,
  },
  survivor: {
    id: "survivor",
    name: "Survivor",
    cost: 1,
    description: "Gain 7 block. Draw 1 card.",
    block: 7,
    draw: 1,
  },
  poisonedStab: {
    id: "poisonedStab",
    name: "Poisoned Stab",
    cost: 1,
    description: "Deal 5 damage. Apply 3 Poison.",
    damage: 5,
    poison: 3,
  },
  deadlyPoison: {
    id: "deadlyPoison",
    name: "Deadly Poison",
    cost: 1,
    description: "Apply 5 Poison.",
    poison: 5,
  },
  backstab: {
    id: "backstab",
    name: "Backstab",
    cost: 0,
    description: "Deal 9 damage.",
    keywords: ["ethereal"],
    damage: 9,
  },
  daggerThrow: {
    id: "daggerThrow",
    name: "Dagger Throw",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  acrobatics: {
    id: "acrobatics",
    name: "Acrobatics",
    cost: 1,
    description: "Draw 3 cards.",
    draw: 3,
  },
  escapePlan: {
    id: "escapePlan",
    name: "Escape Plan",
    cost: 0,
    description: "Gain 4 block. Draw 1 card.",
    block: 4,
    draw: 1,
  },
  flyingKnee: {
    id: "flyingKnee",
    name: "Flying Knee",
    cost: 1,
    description: "Deal 8 damage. Gain 1 energy.",
    damage: 8,
    energy: 1,
  },
  quickSlash: {
    id: "quickSlash",
    name: "Quick Slash",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  backflip: {
    id: "backflip",
    name: "Backflip",
    cost: 1,
    description: "Gain 6 block. Draw 2 cards.",
    block: 6,
    draw: 2,
  },
  deflect: {
    id: "deflect",
    name: "Deflect",
    cost: 0,
    description: "Gain 4 block.",
    block: 4,
  },
  suckerPunch: {
    id: "suckerPunch",
    name: "Sucker Punch",
    cost: 1,
    description: "Deal 6 damage. Apply 1 Weak.",
    damage: 6,
    weak: 1,
  },
  terror: {
    id: "terror",
    name: "Terror",
    cost: 1,
    description: "Apply 2 Vulnerable.",
    vulnerable: 2,
  },
  outmaneuver: {
    id: "outmaneuver",
    name: "Outmaneuver",
    cost: 1,
    description: "Gain 2 energy.",
    keywords: ["retain"],
    energy: 2,
    retain: true,
  },
  legSweep: {
    id: "legSweep",
    name: "Leg Sweep",
    cost: 2,
    description: "Gain 9 block. Apply 2 Weak.",
    block: 9,
    weak: 2,
  },
  dash: {
    id: "dash",
    name: "Dash",
    cost: 2,
    description: "Deal 10 damage. Gain 10 block.",
    damage: 10,
    block: 10,
  },
  predator: {
    id: "predator",
    name: "Predator",
    cost: 2,
    description: "Deal 12 damage. Draw 2 cards.",
    damage: 12,
    draw: 2,
  },
  cripplingCloud: {
    id: "cripplingCloud",
    name: "Crippling Cloud",
    cost: 2,
    description: "Apply 4 Poison. Apply 1 Weak.",
    poison: 4,
    weak: 1,
  },
  catalyst: {
    id: "catalyst",
    name: "Catalyst",
    cost: 1,
    description: "Multiply Poison by 2.",
    keywords: ["exhaust"],
    poisonMultiplier: 2,
    exhaust: true,
  },
  adrenaline: {
    id: "adrenaline",
    name: "Adrenaline",
    cost: 0,
    description: "Draw 2 cards. Gain 1 energy.",
    keywords: ["exhaust"],
    draw: 2,
    energy: 1,
    exhaust: true,
  },
  glassKnife: {
    id: "glassKnife",
    name: "Glass Knife",
    cost: 2,
    description: "Deal 18 damage.",
    keywords: ["ethereal"],
    damage: 18,
  },
  piercingWail: {
    id: "piercingWail",
    name: "Piercing Wail",
    cost: 1,
    description: "Apply 2 Weak.",
    keywords: ["exhaust"],
    weak: 2,
    exhaust: true,
  },
  bouncingFlask: {
    id: "bouncingFlask",
    name: "Bouncing Flask",
    cost: 2,
    description: "Apply 7 Poison.",
    poison: 7,
  },
  heelHook: {
    id: "heelHook",
    name: "Heel Hook",
    cost: 1,
    description: "Deal 8 damage. Apply 1 Weak. Draw 1 card.",
    damage: 8,
    weak: 1,
    draw: 1,
  },
  deadlyTactics: {
    id: "deadlyTactics",
    name: "Deadly Tactics",
    cost: 1,
    description: "Gain 1 energy. Draw 2 cards.",
    keywords: ["retain"],
    energy: 1,
    draw: 2,
    retain: true,
  },
  finisher: {
    id: "finisher",
    name: "Finisher",
    cost: 2,
    description: "Deal 16 damage.",
    damage: 16,
  },
};

type CardStats = Omit<CardTemplate, "id" | "name">;

function withKeyword(keywords: CardStats["keywords"], keyword: NonNullable<CardStats["keywords"]>[number]) {
  return keywords?.includes(keyword) ? keywords : [...(keywords ?? []), keyword];
}

function upgradeDamage(amount: number): number {
  if (amount >= 18) return amount + 6;
  if (amount >= 10) return amount + 4;
  return amount + 3;
}

function upgradeBlock(amount: number): number {
  if (amount >= 18) return amount + 8;
  if (amount >= 10) return amount + 5;
  return amount + 3;
}

function formatDescription(stats: CardStats): string {
  const lines: string[] = [];

  if (stats.damage) lines.push(`Deal ${stats.damage} damage.`);
  if (stats.block) lines.push(`Gain ${stats.block} block.`);
  if (stats.draw) lines.push(`Draw ${stats.draw} card${stats.draw === 1 ? "" : "s"}.`);
  if (stats.energy) lines.push(`Gain ${stats.energy} energy.`);
  if (stats.heal) lines.push(`Recover ${stats.heal} HP.`);
  if (stats.weak) lines.push(`Apply ${stats.weak} Weak.`);
  if (stats.vulnerable) lines.push(`Apply ${stats.vulnerable} Vulnerable.`);
  if (stats.poison) lines.push(`Apply ${stats.poison} Poison.`);
  if (stats.poisonMultiplier && stats.poisonMultiplier !== 1) lines.push(`Multiply Poison by ${stats.poisonMultiplier}.`);

  return lines.join(" ");
}

function buildUpgradedStats(id: string, stats: CardStats): CardStats {
  const upgraded: CardStats = { ...stats };

  if (upgraded.damage) upgraded.damage = upgradeDamage(upgraded.damage);
  if (upgraded.block) upgraded.block = upgradeBlock(upgraded.block);
  if (upgraded.draw) upgraded.draw += 1;
  if (upgraded.energy) upgraded.energy += 1;
  if (upgraded.heal) upgraded.heal += 2;
  if (upgraded.weak) upgraded.weak += 1;
  if (upgraded.vulnerable) upgraded.vulnerable += 1;
  if (upgraded.poison) upgraded.poison += 2;

  if (id === "battleTrance" || id === "bloodletting" || id === "adrenaline") {
    upgraded.keywords = withKeyword(upgraded.keywords, "exhaust");
  }

  if (id === "executioner" || id === "glassKnife") {
    upgraded.keywords = withKeyword(upgraded.keywords, "ethereal");
  }

  upgraded.description = formatDescription(upgraded);
  return upgraded;
}

const toUpgradableCard = (card: CardTemplate): CardDefinition => {
  const { id, name, ...stats } = card;
  const rarity: CardRarity = CARD_RARITY_BY_ID[id] ?? "common";
  const upgraded = buildUpgradedStats(id, stats);

  return {
    id,
    name,
    ...stats,
    rarity,
    base: { ...stats },
    upgraded,
  } as CardDefinition;
};

export const cards = Object.fromEntries(
  Object.entries(baseCards).map(([id, card]) => [id, toUpgradableCard({ ...card, id } as CardTemplate)]),
) as unknown as Record<string, CardDefinition>;
