import type { CardDefinition } from "@towerlab/core";

export const cards: Record<string, CardDefinition> = {
  strike: {
    id: "strike",
    name: "Strike",
    cost: 1,
    description: "Deal 6 damage.",
    damage: 6,
  },
  defend: {
    id: "defend",
    name: "Defend",
    cost: 1,
    description: "Gain 5 block.",
    block: 5,
  },
  surge: {
    id: "surge",
    name: "Surge",
    cost: 1,
    description: "Deal 4 damage. Gain 4 block.",
    damage: 4,
    block: 4,
  },
  quickGuard: {
    id: "quickGuard",
    name: "Quick Guard",
    cost: 1,
    description: "Gain 7 block.",
    block: 7,
  },
  punishingHit: {
    id: "punishingHit",
    name: "Punishing Hit",
    cost: 2,
    description: "Deal 9 damage.",
    damage: 9,
  },
  heavyBlow: {
    id: "heavyBlow",
    name: "Heavy Blow",
    cost: 2,
    description: "Deal 11 damage.",
    damage: 11,
  },
  precision: {
    id: "precision",
    name: "Precision",
    cost: 2,
    description: "Deal 6 damage. Gain 2 block.",
    damage: 6,
    block: 2,
  },
  recklessLunge: {
    id: "recklessLunge",
    name: "Reckless Lunge",
    cost: 1,
    description: "Deal 8 damage.",
    damage: 8,
  },
  ironTempo: {
    id: "ironTempo",
    name: "Iron Tempo",
    cost: 2,
    description: "Deal 8 damage. Gain 6 block.",
    damage: 8,
    block: 6,
  },
  executioner: {
    id: "executioner",
    name: "Executioner",
    cost: 2,
    description: "Deal 14 damage.",
    damage: 14,
  },
  brace: {
    id: "brace",
    name: "Brace",
    cost: 1,
    description: "Gain 7 block.",
    block: 7,
  },
  shieldJab: {
    id: "shieldJab",
    name: "Shield Jab",
    cost: 1,
    description: "Deal 6 damage. Gain 2 block.",
    damage: 6,
    block: 2,
  },
  safeguard: {
    id: "safeguard",
    name: "Safeguard",
    cost: 1,
    description: "Gain 9 block.",
    block: 9,
  },
  towerSlam: {
    id: "towerSlam",
    name: "Tower Slam",
    cost: 2,
    description: "Deal 11 damage. Gain 5 block.",
    damage: 11,
    block: 5,
  },
  holdFast: {
    id: "holdFast",
    name: "Hold Fast",
    cost: 1,
    description: "Gain 9 block.",
    block: 9,
  },
  riposte: {
    id: "riposte",
    name: "Riposte",
    cost: 1,
    description: "Deal 8 damage. Gain 2 block.",
    damage: 8,
    block: 2,
  },
  citadel: {
    id: "citadel",
    name: "Citadel",
    cost: 2,
    description: "Gain 9 block. Deal 7 damage.",
    damage: 7,
    block: 9,
  },
  lastStand: {
    id: "lastStand",
    name: "Last Stand",
    cost: 2,
    description: "Deal 9 damage. Gain 9 block.",
    damage: 9,
    block: 9,
  },
  bastion: {
    id: "bastion",
    name: "Bastion",
    cost: 2,
    description: "Gain 12 block.",
    block: 12,
  },
};
