import type { EnemyDefinition } from "@towerlab/core";

export const enemies: Record<string, EnemyDefinition> = {
  sentry: {
    id: "sentry",
    name: "Sentry",
    maxHp: 24,
    goldReward: 16,
    intents: [
      { kind: "attack", description: "Jab for 5", damage: 5 },
      { kind: "block", description: "Brace for 6 block", block: 6 },
      { kind: "attack", description: "Lunge for 7", damage: 7 },
    ],
  },
  raider: {
    id: "raider",
    name: "Raider",
    maxHp: 27,
    goldReward: 18,
    intents: [
      { kind: "attack", description: "Slash for 6", damage: 6 },
      { kind: "attackBlock", description: "Press for 6 and gain 3 block", damage: 6, block: 3 },
      { kind: "attack", description: "Rush for 8", damage: 8 },
    ],
  },
  skirmisher: {
    id: "skirmisher",
    name: "Skirmisher",
    maxHp: 25,
    goldReward: 17,
    intents: [
      { kind: "attackBlock", description: "Feint for 4 and gain 3 block", damage: 4, block: 3 },
      { kind: "attack", description: "Slice for 7", damage: 7 },
      { kind: "block", description: "Guard for 6 block", block: 6 },
    ],
  },
  emberAdept: {
    id: "emberAdept",
    name: "Ember Adept",
    maxHp: 26,
    goldReward: 19,
    intents: [
      { kind: "attack", description: "Spark for 6", damage: 6 },
      { kind: "block", description: "Stoke 5 block", block: 5 },
      { kind: "attack", description: "Scorch for 8", damage: 8 },
    ],
  },
  crusher: {
    id: "crusher",
    name: "Crusher",
    maxHp: 40,
    goldReward: 27,
    intents: [
      { kind: "attackBlock", description: "Crush for 8 and gain 4 block", damage: 8, block: 4 },
      { kind: "heal", description: "Patch 6 HP", heal: 6 },
      { kind: "attack", description: "Hammer for 12", damage: 12 },
    ],
  },
  bannerCaptain: {
    id: "bannerCaptain",
    name: "Banner Captain",
    maxHp: 46,
    goldReward: 29,
    intents: [
      { kind: "attackBlock", description: "Command for 8 and gain 5 block", damage: 8, block: 5 },
      { kind: "block", description: "Brace for 8 block", block: 8 },
      { kind: "attack", description: "Cleave for 12", damage: 12 },
    ],
  },
  forgeKeeper: {
    id: "forgeKeeper",
    name: "Forge Keeper",
    maxHp: 72,
    goldReward: 48,
    intents: [
      { kind: "attackBlock", description: "Smash for 10 and gain 4 block", damage: 10, block: 4 },
      { kind: "block", description: "Temper 8 block", block: 8 },
      { kind: "attack", description: "Crush for 14", damage: 14 },
    ],
  },
  ironColossus: {
    id: "ironColossus",
    name: "Iron Colossus",
    maxHp: 78,
    goldReward: 52,
    intents: [
      { kind: "attack", description: "Trample for 16", damage: 16 },
      { kind: "block", description: "Raise 10 block", block: 10 },
      { kind: "attackBlock", description: "Hammer for 13 and gain 4 block", damage: 13, block: 4 },
      { kind: "heal", description: "Reforge 8 HP", heal: 8 },
    ],
  },
  watcher: {
    id: "watcher",
    name: "Watcher",
    maxHp: 34,
    goldReward: 23,
    intents: [
      { kind: "attack", description: "Pulse for 7", damage: 7 },
      { kind: "block", description: "Charge 7 block", block: 7 },
      { kind: "attackBlock", description: "Overwatch for 9 and gain 3 block", damage: 9, block: 3 },
    ],
  },
  boltHound: {
    id: "boltHound",
    name: "Bolt Hound",
    maxHp: 32,
    goldReward: 24,
    intents: [
      { kind: "attack", description: "Snap for 6", damage: 6 },
      { kind: "heal", description: "Recover 6 HP", heal: 6 },
      { kind: "attack", description: "Arc Bite for 11", damage: 11 },
    ],
  },
  lensAdept: {
    id: "lensAdept",
    name: "Lens Adept",
    maxHp: 35,
    goldReward: 25,
    intents: [
      { kind: "attack", description: "Beam for 8", damage: 8 },
      { kind: "block", description: "Ward 7 block", block: 7 },
      { kind: "attackBlock", description: "Align for 7 and gain 3 block", damage: 7, block: 3 },
    ],
  },
  circuitMantis: {
    id: "circuitMantis",
    name: "Circuit Mantis",
    maxHp: 33,
    goldReward: 24,
    intents: [
      { kind: "attack", description: "Snap for 7", damage: 7 },
      { kind: "block", description: "Charge 6 block", block: 6 },
      { kind: "attack", description: "Arc Lash for 9", damage: 9 },
    ],
  },
  watchCore: {
    id: "watchCore",
    name: "Watch Core",
    maxHp: 52,
    goldReward: 34,
    intents: [
      { kind: "block", description: "Charge 8 block", block: 8 },
      { kind: "attack", description: "Pulse for 11", damage: 11 },
      { kind: "attackBlock", description: "Overload for 14 and gain 5 block", damage: 14, block: 5 },
    ],
  },
  stormBishop: {
    id: "stormBishop",
    name: "Storm Bishop",
    maxHp: 55,
    goldReward: 36,
    intents: [
      { kind: "attack", description: "Bolt for 11", damage: 11 },
      { kind: "block", description: "Sanctify 8 block", block: 8 },
      { kind: "attackBlock", description: "Stormcall for 10 and gain 5 block", damage: 10, block: 5 },
      { kind: "heal", description: "Recover 6 HP", heal: 6 },
    ],
  },
  spireWarden: {
    id: "spireWarden",
    name: "Spire Warden",
    maxHp: 82,
    goldReward: 58,
    intents: [
      { kind: "block", description: "Raise 10 block", block: 10 },
      { kind: "attack", description: "Judgment for 13", damage: 13 },
      { kind: "attackBlock", description: "Seal for 16 and gain 6 block", damage: 16, block: 6 },
    ],
  },
  tempestPrism: {
    id: "tempestPrism",
    name: "Tempest Prism",
    maxHp: 86,
    goldReward: 62,
    intents: [
      { kind: "attack", description: "Prism Beam for 15", damage: 15 },
      { kind: "block", description: "Polarize 11 block", block: 11 },
      { kind: "attackBlock", description: "Static Burst for 12 and gain 5 block", damage: 12, block: 5 },
      { kind: "heal", description: "Recharge 8 HP", heal: 8 },
    ],
  },
  ashenKnight: {
    id: "ashenKnight",
    name: "Ashen Knight",
    maxHp: 40,
    goldReward: 28,
    intents: [
      { kind: "attack", description: "Cleave for 10", damage: 10 },
      { kind: "attackBlock", description: "Guarded swing for 12 and gain 4 block", damage: 12, block: 4 },
      { kind: "heal", description: "Steady 6 HP", heal: 6 },
    ],
  },
  voidPriest: {
    id: "voidPriest",
    name: "Void Priest",
    maxHp: 38,
    goldReward: 29,
    intents: [
      { kind: "block", description: "Ward 10 block", block: 10 },
      { kind: "attack", description: "Blast for 12", damage: 12 },
      { kind: "attackBlock", description: "Rift for 10 and gain 6 block", damage: 10, block: 6 },
    ],
  },
  mawSentinel: {
    id: "mawSentinel",
    name: "Maw Sentinel",
    maxHp: 43,
    goldReward: 31,
    intents: [
      { kind: "attack", description: "Maul for 11", damage: 11 },
      { kind: "block", description: "Brace for 8 block", block: 8 },
      { kind: "attackBlock", description: "Rend for 10 and gain 4 block", damage: 10, block: 4 },
    ],
  },
  ruinStalker: {
    id: "ruinStalker",
    name: "Ruin Stalker",
    maxHp: 41,
    goldReward: 30,
    intents: [
      { kind: "attack", description: "Pounce for 12", damage: 12 },
      { kind: "block", description: "Harden 9 block", block: 9 },
      { kind: "attackBlock", description: "Stalk for 9 and gain 4 block", damage: 9, block: 4 },
    ],
  },
  grimEngine: {
    id: "grimEngine",
    name: "Grim Engine",
    maxHp: 62,
    goldReward: 42,
    intents: [
      { kind: "attackBlock", description: "Drive for 15 and gain 6 block", damage: 15, block: 6 },
      { kind: "heal", description: "Refit 8 HP", heal: 8 },
      { kind: "attack", description: "Overrun for 18", damage: 18 },
    ],
  },
  hollowRegent: {
    id: "hollowRegent",
    name: "Hollow Regent",
    maxHp: 67,
    goldReward: 44,
    intents: [
      { kind: "attack", description: "Edict for 14", damage: 14 },
      { kind: "block", description: "Ward 12 block", block: 12 },
      { kind: "attackBlock", description: "Crush for 12 and gain 6 block", damage: 12, block: 6 },
      { kind: "heal", description: "Recover 8 HP", heal: 8 },
    ],
  },
  ancientTitan: {
    id: "ancientTitan",
    name: "Ancient Titan",
    maxHp: 98,
    goldReward: 74,
    intents: [
      { kind: "block", description: "Fortify 12 block", block: 12 },
      { kind: "attack", description: "Quake for 16", damage: 16 },
      { kind: "attackBlock", description: "Cataclysm for 20 and gain 8 block", damage: 20, block: 8 },
    ],
  },
  voidSovereign: {
    id: "voidSovereign",
    name: "Void Sovereign",
    maxHp: 104,
    goldReward: 78,
    intents: [
      { kind: "attack", description: "Void Lance for 18", damage: 18 },
      { kind: "block", description: "Aegis 14 block", block: 14 },
      { kind: "attackBlock", description: "Dominate for 16 and gain 7 block", damage: 16, block: 7 },
      { kind: "heal", description: "Devour 10 HP", heal: 10 },
    ],
  },
};
