import type { RelicDefinition } from "@towerlab/core";

export const relics: Record<string, RelicDefinition> = {
  battleStandard: {
    id: "battleStandard",
    name: "Battle Standard",
    description: "Start each combat with +1 block.",
    kind: "combatStartBlock",
    value: 1,
  },
  fieldKit: {
    id: "fieldKit",
    name: "Field Kit",
    description: "Recover +2 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 2,
  },
  combatFocus: {
    id: "combatFocus",
    name: "Combat Focus",
    description: "Gain 1 extra energy at the start of each combat.",
    kind: "combatEnergy",
    value: 1,
  },
  bucklerFrame: {
    id: "bucklerFrame",
    name: "Buckler Frame",
    description: "Start each combat with +2 block.",
    kind: "combatStartBlock",
    value: 2,
  },
  reinforcedFrame: {
    id: "reinforcedFrame",
    name: "Reinforced Frame",
    description: "Gain 12 max HP.",
    kind: "maxHp",
    value: 12,
  },
  medicinePack: {
    id: "medicinePack",
    name: "Medicine Pack",
    description: "Recover +3 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 3,
  },
  merchantTag: {
    id: "merchantTag",
    name: "Merchant Tag",
    description: "Shop cards cost 1 less.",
    kind: "shopDiscount",
    value: 1,
  },
  razorsigil: {
    id: "razorsigil",
    name: "Razor Sigil",
    description: "Start each combat with +3 block.",
    kind: "combatStartBlock",
    value: 3,
  },
  warEngine: {
    id: "warEngine",
    name: "War Engine",
    description: "Gain 1 extra energy at the start of each combat.",
    kind: "combatEnergy",
    value: 1,
  },
  berserkerCharm: {
    id: "berserkerCharm",
    name: "Berserker Charm",
    description: "Gain 1 extra energy at the start of each combat.",
    kind: "combatEnergy",
    value: 1,
  },
  fieldTonic: {
    id: "fieldTonic",
    name: "Field Tonic",
    description: "Recover +3 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 3,
  },
  scavengerMark: {
    id: "scavengerMark",
    name: "Scavenger Mark",
    description: "Shop cards cost 1 less.",
    kind: "shopDiscount",
    value: 1,
  },
  warPaint: {
    id: "warPaint",
    name: "War Paint",
    description: "Start each combat with +2 block.",
    kind: "combatStartBlock",
    value: 2,
  },
  conquestFrame: {
    id: "conquestFrame",
    name: "Conquest Frame",
    description: "Gain 10 max HP.",
    kind: "maxHp",
    value: 10,
  },
  emberCrest: {
    id: "emberCrest",
    name: "Ember Crest",
    description: "Start each combat with +5 block.",
    kind: "combatStartBlock",
    value: 5,
  },
  guardTraining: {
    id: "guardTraining",
    name: "Guard Training",
    description: "Start each combat with +3 block.",
    kind: "combatStartBlock",
    value: 3,
  },
  reservePlate: {
    id: "reservePlate",
    name: "Reserve Plate",
    description: "Gain 8 max HP.",
    kind: "maxHp",
    value: 8,
  },
  wardCharm: {
    id: "wardCharm",
    name: "Ward Charm",
    description: "Recover +4 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 4,
  },
  caravanSeal: {
    id: "caravanSeal",
    name: "Caravan Seal",
    description: "Shop cards cost 1 less.",
    kind: "shopDiscount",
    value: 1,
  },
  bulwarkCore: {
    id: "bulwarkCore",
    name: "Bulwark Core",
    description: "Start each combat with +4 block.",
    kind: "combatStartBlock",
    value: 4,
  },
  sentryGreaves: {
    id: "sentryGreaves",
    name: "Sentry Greaves",
    description: "Start each combat with +2 block.",
    kind: "combatStartBlock",
    value: 2,
  },
  quartermasterSeal: {
    id: "quartermasterSeal",
    name: "Quartermaster Seal",
    description: "Shop cards cost 1 less.",
    kind: "shopDiscount",
    value: 1,
  },
  triageKit: {
    id: "triageKit",
    name: "Triage Kit",
    description: "Recover +3 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 3,
  },
  garrisonPlate: {
    id: "garrisonPlate",
    name: "Garrison Plate",
    description: "Gain 8 max HP.",
    kind: "maxHp",
    value: 8,
  },
  holdfastEngine: {
    id: "holdfastEngine",
    name: "Holdfast Engine",
    description: "Gain 1 extra energy at the start of each combat.",
    kind: "combatEnergy",
    value: 1,
  },
  citadelFrame: {
    id: "citadelFrame",
    name: "Citadel Frame",
    description: "Gain 10 max HP.",
    kind: "maxHp",
    value: 10,
  },
};
