import type { RelicDefinition } from "@towerlab/core";

export const relics: Record<string, RelicDefinition> = {
  battleStandard: {
    id: "battleStandard",
    name: "Battle Standard",
    description: "Start each combat with +1 block.",
    kind: "combatStartBlock",
    value: 1,
  },
  fieldKit: {
    id: "fieldKit",
    name: "Field Kit",
    description: "Recover +2 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 2,
  },
  combatFocus: {
    id: "combatFocus",
    name: "Combat Focus",
    description: "Gain 1 extra energy at the start of each combat.",
    kind: "combatEnergy",
    value: 1,
  },
  bucklerFrame: {
    id: "bucklerFrame",
    name: "Buckler Frame",
    description: "Start each combat with +2 block.",
    kind: "combatStartBlock",
    value: 2,
  },
  reinforcedFrame: {
    id: "reinforcedFrame",
    name: "Reinforced Frame",
    description: "Gain 12 max HP.",
    kind: "maxHp",
    value: 12,
  },
  medicinePack: {
    id: "medicinePack",
    name: "Medicine Pack",
    description: "Recover +3 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 3,
  },
  merchantTag: {
    id: "merchantTag",
    name: "Merchant Tag",
    description: "Shop cards cost 1 less.",
    kind: "shopDiscount",
    value: 1,
  },
  razorsigil: {
    id: "razorsigil",
    name: "Razor Sigil",
    description: "Start each combat with +3 block.",
    kind: "combatStartBlock",
    value: 3,
  },
  warEngine: {
    id: "warEngine",
    name: "War Engine",
    description: "Gain 1 extra energy at the start of each combat.",
    kind: "combatEnergy",
    value: 1,
  },
  guardTraining: {
    id: "guardTraining",
    name: "Guard Training",
    description: "Start each combat with +3 block.",
    kind: "combatStartBlock",
    value: 3,
  },
  reservePlate: {
    id: "reservePlate",
    name: "Reserve Plate",
    description: "Gain 8 max HP.",
    kind: "maxHp",
    value: 8,
  },
  wardCharm: {
    id: "wardCharm",
    name: "Ward Charm",
    description: "Recover +4 HP from campfire recovery.",
    kind: "restHealBonus",
    value: 4,
  },
  caravanSeal: {
    id: "caravanSeal",
    name: "Caravan Seal",
    description: "Shop cards cost 1 less.",
    kind: "shopDiscount",
    value: 1,
  },
  bulwarkCore: {
    id: "bulwarkCore",
    name: "Bulwark Core",
    description: "Start each combat with +4 block.",
    kind: "combatStartBlock",
    value: 4,
  },
};
