import type { CardTemplate } from "./template.js";

export const hunterCardIds = [
  "slice",
  "dodge",
  "neutralize",
  "survivor",
  "poisonedStab",
  "deadlyPoison",
  "backstab",
  "daggerThrow",
  "acrobatics",
  "escapePlan",
  "flyingKnee",
  "quickSlash",
  "backflip",
  "deflect",
  "suckerPunch",
  "terror",
  "outmaneuver",
  "legSweep",
  "dash",
  "predator",
  "cripplingCloud",
  "catalyst",
  "piercingWail",
  "bouncingFlask",
  "heelHook",
  "deadlyTactics",
  "glassKnife",
  "adrenaline",
  "finisher",
  "markedShot",
  "nightbrew",
  "markedQuarry",
  "cruelTutelage",
] as const;

export const hunterCardTemplates: Record<string, CardTemplate> = {
  slice: {
    id: "slice",
    name: "Slice",
    cost: 1,
    description: "Deal 5 damage.",
    damage: 5,
  },
  dodge: {
    id: "dodge",
    name: "Dodge",
    cost: 1,
    description: "Gain 5 block.",
    block: 5,
  },
  neutralize: {
    id: "neutralize",
    name: "Neutralize",
    cost: 0,
    description: "Deal 3 damage. Apply 1 Weak.",
    damage: 3,
    weak: 1,
  },
  survivor: {
    id: "survivor",
    name: "Survivor",
    cost: 1,
    description: "Gain 7 block. Draw 1 card.",
    block: 7,
    draw: 1,
  },
  poisonedStab: {
    id: "poisonedStab",
    name: "Poisoned Stab",
    cost: 1,
    description: "Deal 5 damage. Apply 3 Poison.",
    damage: 5,
    poison: 3,
  },
  deadlyPoison: {
    id: "deadlyPoison",
    name: "Deadly Poison",
    cost: 1,
    description: "Apply 5 Poison.",
    poison: 5,
  },
  backstab: {
    id: "backstab",
    name: "Backstab",
    cost: 0,
    description: "Deal 9 damage.",
    keywords: ["ethereal"],
    damage: 9,
  },
  daggerThrow: {
    id: "daggerThrow",
    name: "Dagger Throw",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  acrobatics: {
    id: "acrobatics",
    name: "Acrobatics",
    cost: 1,
    description: "Draw 3 cards.",
    draw: 3,
  },
  escapePlan: {
    id: "escapePlan",
    name: "Escape Plan",
    cost: 0,
    description: "Gain 4 block. Draw 1 card.",
    block: 4,
    draw: 1,
  },
  flyingKnee: {
    id: "flyingKnee",
    name: "Flying Knee",
    cost: 1,
    description: "Deal 8 damage. Gain 1 energy.",
    damage: 8,
    energy: 1,
  },
  quickSlash: {
    id: "quickSlash",
    name: "Quick Slash",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  backflip: {
    id: "backflip",
    name: "Backflip",
    cost: 1,
    description: "Gain 6 block. Draw 2 cards.",
    block: 6,
    draw: 2,
  },
  deflect: {
    id: "deflect",
    name: "Deflect",
    cost: 0,
    description: "Gain 4 block.",
    block: 4,
  },
  suckerPunch: {
    id: "suckerPunch",
    name: "Sucker Punch",
    cost: 1,
    description: "Deal 6 damage. Apply 1 Weak.",
    damage: 6,
    weak: 1,
  },
  terror: {
    id: "terror",
    name: "Terror",
    cost: 1,
    description: "Apply 2 Vulnerable.",
    vulnerable: 2,
  },
  outmaneuver: {
    id: "outmaneuver",
    name: "Outmaneuver",
    cost: 1,
    description: "Gain 2 energy.",
    keywords: ["retain"],
    energy: 2,
    retain: true,
  },
  legSweep: {
    id: "legSweep",
    name: "Leg Sweep",
    cost: 2,
    description: "Gain 9 block. Apply 2 Weak.",
    block: 9,
    weak: 2,
  },
  dash: {
    id: "dash",
    name: "Dash",
    cost: 2,
    description: "Deal 10 damage. Gain 10 block.",
    damage: 10,
    block: 10,
  },
  predator: {
    id: "predator",
    name: "Predator",
    cost: 2,
    description: "Deal 12 damage. Draw 2 cards.",
    damage: 12,
    draw: 2,
  },
  cripplingCloud: {
    id: "cripplingCloud",
    name: "Crippling Cloud",
    cost: 2,
    description: "Apply 4 Poison. Apply 1 Weak.",
    poison: 4,
    weak: 1,
  },
  catalyst: {
    id: "catalyst",
    name: "Catalyst",
    cost: 1,
    description: "Multiply Poison by 2.",
    keywords: ["exhaust"],
    poisonMultiplier: 2,
    exhaust: true,
  },
  adrenaline: {
    id: "adrenaline",
    name: "Adrenaline",
    cost: 0,
    description: "Draw 2 cards. Gain 1 energy.",
    keywords: ["exhaust"],
    draw: 2,
    energy: 1,
    exhaust: true,
  },
  glassKnife: {
    id: "glassKnife",
    name: "Glass Knife",
    cost: 2,
    description: "Deal 18 damage.",
    keywords: ["ethereal"],
    damage: 18,
  },
  piercingWail: {
    id: "piercingWail",
    name: "Piercing Wail",
    cost: 1,
    description: "Apply 2 Weak.",
    keywords: ["exhaust"],
    weak: 2,
    exhaust: true,
  },
  bouncingFlask: {
    id: "bouncingFlask",
    name: "Bouncing Flask",
    cost: 2,
    description: "Apply 7 Poison.",
    poison: 7,
  },
  heelHook: {
    id: "heelHook",
    name: "Heel Hook",
    cost: 1,
    description: "Deal 8 damage. Apply 1 Weak. Draw 1 card.",
    damage: 8,
    weak: 1,
    draw: 1,
  },
  deadlyTactics: {
    id: "deadlyTactics",
    name: "Deadly Tactics",
    cost: 1,
    description: "Gain 1 energy. Draw 2 cards.",
    keywords: ["retain"],
    energy: 1,
    draw: 2,
    retain: true,
  },
  finisher: {
    id: "finisher",
    name: "Finisher",
    cost: 2,
    description: "Deal 16 damage.",
    damage: 16,
  },
  markedShot: {
    id: "markedShot",
    name: "Marked Shot",
    cost: 1,
    description: "Deal 6 damage. Apply 1 Vulnerable.",
    damage: 6,
    vulnerable: 1,
  },
  nightbrew: {
    id: "nightbrew",
    name: "Nightbrew",
    cost: 1,
    description: "Your attacks apply 2 Poison this combat.",
    keywords: ["exhaust"],
    passives: [{ kind: "attackPoison", value: 2 }],
    exhaust: true,
  },
  markedQuarry: {
    id: "markedQuarry",
    name: "Marked Quarry",
    cost: 1,
    description: "Your attacks deal 4 more damage to debuffed enemies this combat.",
    keywords: ["exhaust"],
    passives: [{ kind: "debuffBonusDamage", value: 4 }],
    exhaust: true,
  },
  cruelTutelage: {
    id: "cruelTutelage",
    name: "Cruel Tutelage",
    cost: 1,
    description: "Whenever you apply Weak, Vulnerable, or Poison this combat, draw 1 card.",
    keywords: ["exhaust"],
    passives: [{ kind: "debuffDraw", value: 1 }],
    exhaust: true,
  },
  };
