import type { CardTemplate } from "./template.js";

export const warriorCardIds = [
  "strike",
  "defend",
  "bash",
  "pommelStrike",
  "anger",
  "shrugItOff",
  "trueGrit",
  "twinStrike",
  "ironWave",
  "thunderclap",
  "surge",
  "tempoDrill",
  "bloodPact",
  "rallyLine",
  "disarm",
  "uppercut",
  "carnage",
  "battleTrance",
  "bloodletting",
  "secondWind",
  "shockwave",
  "heavyBlow",
  "warpath",
  "overrun",
  "clothesline",
  "dropkick",
  "ghostlyArmor",
  "impervious",
  "bludgeon",
  "executioner",
  "finalCharge",
  "burningBanner",
  "warSpoils",
  "reaper",
] as const;

export const warriorCardTemplates: Record<string, CardTemplate> = {
  strike: {
    id: "strike",
    name: "Strike",
    cost: 1,
    description: "Deal 6 damage.",
    damage: 6,
  },
  defend: {
    id: "defend",
    name: "Defend",
    cost: 1,
    description: "Gain 5 block.",
    block: 5,
  },
  surge: {
    id: "surge",
    name: "Surge",
    cost: 1,
    description: "Deal 4 damage. Gain 4 block.",
    damage: 4,
    block: 4,
  },
  tempoDrill: {
    id: "tempoDrill",
    name: "Tempo Drill",
    cost: 1,
    description: "Gain 1 energy. Draw 1 card.",
    energy: 1,
    draw: 1,
  },
  bloodPact: {
    id: "bloodPact",
    name: "Blood Pact",
    cost: 1,
    description: "Deal 7 damage. Recover 2 HP.",
    damage: 7,
    heal: 2,
  },
  rallyLine: {
    id: "rallyLine",
    name: "Rally Line",
    cost: 1,
    description: "Gain 6 block. Draw 1 card.",
    block: 6,
    draw: 1,
  },
  warpath: {
    id: "warpath",
    name: "Warpath",
    cost: 2,
    description: "Deal 10 damage. Gain 5 block.",
    damage: 10,
    block: 5,
  },
  secondWind: {
    id: "secondWind",
    name: "Second Wind",
    cost: 2,
    description: "Gain 7 block. Recover 4 HP.",
    keywords: ["exhaust"],
    block: 7,
    heal: 4,
    exhaust: true,
  },
  burningBanner: {
    id: "burningBanner",
    name: "Burning Banner",
    cost: 2,
    description: "Deal 8 damage. Draw 2 cards.",
    damage: 8,
    draw: 2,
  },
  battleTrance: {
    id: "battleTrance",
    name: "Battle Trance",
    cost: 0,
    description: "Draw 2 cards.",
    keywords: ["exhaust"],
    draw: 2,
    exhaust: true,
  },
  bash: {
    id: "bash",
    name: "Bash",
    cost: 2,
    description: "Deal 8 damage. Apply 2 Vulnerable.",
    damage: 8,
    vulnerable: 2,
  },
  pommelStrike: {
    id: "pommelStrike",
    name: "Pommel Strike",
    cost: 1,
    description: "Deal 7 damage. Draw 1 card.",
    damage: 7,
    draw: 1,
  },
  shrugItOff: {
    id: "shrugItOff",
    name: "Shrug It Off",
    cost: 1,
    description: "Gain 8 block. Draw 1 card.",
    block: 8,
    draw: 1,
  },
  anger: {
    id: "anger",
    name: "Anger",
    cost: 0,
    description: "Deal 4 damage.",
    damage: 4,
  },
  trueGrit: {
    id: "trueGrit",
    name: "True Grit",
    cost: 1,
    description: "Gain 7 block.",
    block: 7,
  },
  twinStrike: {
    id: "twinStrike",
    name: "Twin Strike",
    cost: 1,
    description: "Deal 8 damage.",
    damage: 8,
  },
  ironWave: {
    id: "ironWave",
    name: "Iron Wave",
    cost: 1,
    description: "Deal 5 damage. Gain 5 block.",
    damage: 5,
    block: 5,
  },
  thunderclap: {
    id: "thunderclap",
    name: "Thunderclap",
    cost: 1,
    description: "Deal 4 damage. Apply 1 Vulnerable.",
    damage: 4,
    vulnerable: 1,
  },
  disarm: {
    id: "disarm",
    name: "Disarm",
    cost: 1,
    description: "Apply 2 Weak.",
    weak: 2,
  },
  bloodletting: {
    id: "bloodletting",
    name: "Bloodletting",
    cost: 0,
    description: "Gain 2 energy.",
    keywords: ["exhaust"],
    energy: 2,
    exhaust: true,
  },
  carnage: {
    id: "carnage",
    name: "Carnage",
    cost: 2,
    description: "Deal 18 damage.",
    keywords: ["retain"],
    damage: 18,
    retain: true,
  },
  uppercut: {
    id: "uppercut",
    name: "Uppercut",
    cost: 2,
    description: "Deal 11 damage. Apply 1 Weak. Apply 1 Vulnerable.",
    damage: 11,
    weak: 1,
    vulnerable: 1,
  },
  shockwave: {
    id: "shockwave",
    name: "Shockwave",
    cost: 2,
    description: "Apply 2 Weak. Apply 2 Vulnerable.",
    keywords: ["exhaust"],
    weak: 2,
    vulnerable: 2,
    exhaust: true,
  },
  heavyBlow: {
    id: "heavyBlow",
    name: "Heavy Blow",
    cost: 2,
    description: "Deal 11 damage.",
    damage: 11,
  },
  impervious: {
    id: "impervious",
    name: "Impervious",
    cost: 2,
    description: "Gain 20 block.",
    keywords: ["exhaust"],
    block: 20,
    exhaust: true,
  },
  bludgeon: {
    id: "bludgeon",
    name: "Bludgeon",
    cost: 3,
    description: "Deal 24 damage.",
    damage: 24,
  },
  clothesline: {
    id: "clothesline",
    name: "Clothesline",
    cost: 2,
    description: "Deal 12 damage. Apply 2 Weak.",
    damage: 12,
    weak: 2,
  },
  dropkick: {
    id: "dropkick",
    name: "Dropkick",
    cost: 1,
    description: "Deal 8 damage. Draw 1 card.",
    damage: 8,
    draw: 1,
  },
  ghostlyArmor: {
    id: "ghostlyArmor",
    name: "Ghostly Armor",
    cost: 1,
    description: "Gain 10 block.",
    keywords: ["ethereal"],
    block: 10,
  },
  overrun: {
    id: "overrun",
    name: "Overrun",
    cost: 2,
    description: "Deal 13 damage. Recover 3 HP.",
    damage: 13,
    heal: 3,
  },
  warSpoils: {
    id: "warSpoils",
    name: "War Spoils",
    cost: 2,
    description: "Deal 11 damage. Draw 2 cards.",
    damage: 11,
    draw: 2,
  },
  executioner: {
    id: "executioner",
    name: "Executioner",
    cost: 2,
    description: "Deal 14 damage.",
    damage: 14,
  },
  finalCharge: {
    id: "finalCharge",
    name: "Final Charge",
    cost: 3,
    description: "Deal 17 damage.",
    damage: 17,
  },
  reaper: {
    id: "reaper",
    name: "Reaper",
    cost: 3,
    description: "Deal 10 damage. Recover 6 HP.",
    damage: 10,
    heal: 6,
  },
};
