import type { CharacterDefinition } from "@towerlab/core";

export const bulwark: CharacterDefinition = {
  id: "bulwark",
  name: "Bulwark",
  summary: "Heavy defense with blunt counterattacks.",
  maxHp: 88,
  startGold: 8,
  starterDeck: [
    "shieldJab",
    "shieldJab",
    "shieldJab",
    "shieldJab",
    "brace",
    "brace",
    "brace",
    "safeguard",
    "riposte",
    "towerSlam",
  ],
  startingRelicId: "guardTraining",
  blessingCards: ["braceLine", "quarterWatch", "bastionCall"],
  rewardCardPools: {
    common: [
      "brace",
      "shieldJab",
      "guardStep",
      "shieldRush",
      "survey",
      "anchorThrow",
      "reserveDrill",
      "lockstep",
      "refit",
      "fortifyDrill",
      "wardensSignal",
      "fortifySignal",
      "lineWard",
      "rearGuard",
      "braceLine",
      "shieldRelay",
      "quarterWatch",
    ],
    rare: ["safeguard", "wallStance", "gatebreaker", "towerSlam", "holdFast", "riposte", "citadel", "lastStand", "aegisDrive", "keepersOath", "breakFormation", "siegeRam", "watchtower"],
    epic: ["bastion", "stronghold", "citadelBreaker", "bulwarkRecovery", "aegisPulse", "bastionCall"],
  },
  shopCardPools: {
    common: [
      "brace",
      "shieldJab",
      "guardStep",
      "shieldRush",
      "survey",
      "anchorThrow",
      "reserveDrill",
      "lockstep",
      "refit",
      "fortifyDrill",
      "wardensSignal",
      "fortifySignal",
      "lineWard",
      "rearGuard",
      "braceLine",
      "shieldRelay",
      "quarterWatch",
    ],
    rare: [
      "safeguard",
      "wallStance",
      "gatebreaker",
      "towerSlam",
      "holdFast",
      "riposte",
      "citadel",
      "lastStand",
      "aegisDrive",
      "keepersOath",
      "breakFormation",
      "ironAnchor",
      "siegeRam",
      "watchtower",
    ],
    epic: ["bastion", "stronghold", "citadelBreaker", "bulwarkRecovery", "aegisPulse", "rampartBuildup", "bastionCall"],
  },
  relicPools: {
    elite: ["bucklerFrame", "wardCharm", "caravanSeal", "reservePlate", "sentryGreaves", "quartermasterSeal", "triageKit", "garrisonPlate"],
    boss: ["bulwarkCore", "reinforcedFrame", "holdfastEngine", "citadelFrame"],
  },
};
