import type { CharacterDefinition } from "@towerlab/core";

export const hunter: CharacterDefinition = {
  id: "hunter",
  name: "Hunter",
  summary: "Poison, debuffs, and sharp hand management.",
  maxHp: 72,
  startGold: 12,
  starterDeck: [
    "slice",
    "slice",
    "slice",
    "slice",
    "dodge",
    "dodge",
    "dodge",
    "dodge",
    "neutralize",
    "survivor",
  ],
  startingRelicId: "ringOfTheSnake",
  blessingCards: ["deadlyPoison", "backflip", "outmaneuver"],
  rewardCardPools: {
    common: [
      "neutralize",
      "poisonedStab",
      "deadlyPoison",
      "quickSlash",
      "backflip",
      "deflect",
      "suckerPunch",
      "terror",
      "slice",
      "dodge",
      "survivor",
    ],
    rare: ["outmaneuver", "legSweep", "dash", "predator", "cripplingCloud", "catalyst"],
    epic: ["glassKnife", "adrenaline"],
  },
  shopCardPools: {
    common: [
      "neutralize",
      "poisonedStab",
      "deadlyPoison",
      "quickSlash",
      "backflip",
      "deflect",
      "suckerPunch",
      "terror",
      "slice",
      "dodge",
      "survivor",
    ],
    rare: [
      "outmaneuver",
      "legSweep",
      "dash",
      "predator",
      "cripplingCloud",
      "catalyst",
    ],
    epic: ["glassKnife", "adrenaline"],
  },
  relicPools: {
    elite: ["toxicVial", "smokeFlask", "silentSatchel", "needleFan", "snakeOil", "preparedKit", "quartermasterSeal", "triageKit"],
    boss: ["venomCrown", "ringOfTheSerpent", "shadowCloak", "ghostPendant"],
  },
};
