import type { CharacterDefinition } from "@towerlab/core";

export const vanguard: CharacterDefinition = {
  id: "vanguard",
  name: "Vanguard",
  summary: "Burst damage and flexible attacks.",
  maxHp: 80,
  startGold: 0,
  starterDeck: [
    "strike",
    "strike",
    "strike",
    "strike",
    "defend",
    "defend",
    "defend",
    "defend",
    "surge",
    "surge",
  ],
  startingRelicId: "battleStandard",
  blessingCards: ["bloodRush", "battleTrance", "overrun"],
  rewardCardPools: {
    common: [
      "surge",
      "quickGuard",
      "battleJab",
      "advanceStep",
      "recklessLunge",
      "frontlineGuard",
      "momentum",
      "bloodPact",
      "rallyLine",
      "tempoDrill",
      "assaultSignal",
      "vanguardVolley",
      "forgedAdvance",
      "bloodRush",
      "skirmishPlan",
    ],
    rare: [
      "punishingHit",
      "sunderStrike",
      "precision",
      "heavyBlow",
      "ironTempo",
      "warCry",
      "warpath",
      "frenziedCharge",
      "secondWind",
      "advanceSignal",
      "rallySprint",
      "stormAssault",
      "battleTrance",
      "overrun",
      "heldBlade",
    ],
    epic: ["crushingTempo", "executioner", "finalCharge", "burningBanner", "vanguardRecovery", "warSpoils"],
  },
  shopCardPools: {
    common: [
      "surge",
      "quickGuard",
      "battleJab",
      "advanceStep",
      "recklessLunge",
      "frontlineGuard",
      "momentum",
      "bloodPact",
      "rallyLine",
      "tempoDrill",
      "assaultSignal",
      "vanguardVolley",
      "forgedAdvance",
      "bloodRush",
      "skirmishPlan",
    ],
    rare: [
      "punishingHit",
      "sunderStrike",
      "precision",
      "heavyBlow",
      "ironTempo",
      "warCry",
      "warpath",
      "frenziedCharge",
      "secondWind",
      "advanceSignal",
      "rallySprint",
      "stormAssault",
      "battleTrance",
      "overrun",
      "heldBlade",
    ],
    epic: ["crushingTempo", "executioner", "finalCharge", "burningBanner", "vanguardRecovery", "warSpoils"],
  },
  relicPools: {
    elite: ["combatFocus", "medicinePack", "merchantTag", "razorsigil", "berserkerCharm", "fieldTonic", "scavengerMark", "warPaint"],
    boss: ["warEngine", "reinforcedFrame", "conquestFrame", "emberCrest"],
  },
};
