import type { CharacterDefinition } from "@towerlab/core";

export const warrior: CharacterDefinition = {
  id: "warrior",
  name: "Warrior",
  summary: "Heavy hits, recovery, and exhaust-driven tempo.",
  maxHp: 82,
  startGold: 0,
  starterDeck: [
    "strike",
    "strike",
    "strike",
    "strike",
    "defend",
    "defend",
    "defend",
    "defend",
    "bash",
    "pommelStrike",
  ],
  startingRelicId: "burningBlood",
  blessingCards: ["anger", "shrugItOff", "carnage"],
  rewardCardPools: {
    common: [
      "anger",
      "pommelStrike",
      "shrugItOff",
      "bash",
      "trueGrit",
      "surge",
      "battleJab",
      "tempoDrill",
      "bloodPact",
      "rallyLine",
      "disarm",
      "forgedAdvance",
    ],
    rare: [
      "uppercut",
      "carnage",
      "battleTrance",
      "bloodletting",
      "secondWind",
      "shockwave",
      "heavyBlow",
      "warpath",
      "overrun",
    ],
    epic: ["impervious", "bludgeon", "executioner", "finalCharge", "burningBanner", "warSpoils"],
  },
  shopCardPools: {
    common: [
      "anger",
      "pommelStrike",
      "shrugItOff",
      "bash",
      "trueGrit",
      "surge",
      "battleJab",
      "tempoDrill",
      "bloodPact",
      "rallyLine",
      "disarm",
      "forgedAdvance",
    ],
    rare: [
      "uppercut",
      "carnage",
      "battleTrance",
      "bloodletting",
      "secondWind",
      "shockwave",
      "heavyBlow",
      "warpath",
      "overrun",
    ],
    epic: ["impervious", "bludgeon", "executioner", "finalCharge", "burningBanner", "warSpoils"],
  },
  relicPools: {
    elite: ["ironWheel", "meatRation", "battleFocus", "warPaint", "scarTalisman", "scavengerMark", "fieldTonic", "ashenHelm"],
    boss: ["redSkull", "warEngine", "reinforcedFrame", "emberCrest"],
  },
};
